## Asignación calificada por pares: Segmentación y agrupación de vecindarios en Toronto

# Parte 1

In [1]:
import pandas as pd

### Leer la tabla desde la fuente, es decir, la URL de Wikipedia a la Lista de códigos postales de Canadá

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
read_table = pd.read_html(url,header=[0])
df = read_table[0]
df.head(10)

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M6A        North York  Lawrence Heights
6      M6A        North York    Lawrence Manor
7      M7A  Downtown Toronto      Queen's Park
8      M8A      Not assigned      Not assigned
9      M9A      Queen's Park      Not assigned

### Cambiar el nombre de los encabezados de columna

In [3]:
df = df.rename(index=str, columns={'Postcode':'PostalCode','Neighbourhood':'Neighborhood'})
df.head()

  PostalCode           Borough      Neighborhood
0        M1A      Not assigned      Not assigned
1        M2A      Not assigned      Not assigned
2        M3A        North York         Parkwoods
3        M4A        North York  Victoria Village
4        M5A  Downtown Toronto      Harbourfront

### Ignorar las celdas con un municipio que no está asignado.

In [4]:
df = df[df.Borough !='Not assigned']
df.reset_index(drop=True,inplace=True)
df.head()

  PostalCode           Borough      Neighborhood
0        M3A        North York         Parkwoods
1        M4A        North York  Victoria Village
2        M5A  Downtown Toronto      Harbourfront
3        M6A        North York  Lawrence Heights
4        M6A        North York    Lawrence Manor

### Agrupamiento de Neighborhood basado en el mismo código postal

In [5]:
df = df.groupby('PostalCode',as_index=False).agg(lambda x: ','.join(set(x.dropna())))
df.head()

  PostalCode      Borough                          Neighborhood
0        M1B  Scarborough                         Rouge,Malvern
1        M1C  Scarborough  Port Union,Highland Creek,Rouge Hill
2        M1E  Scarborough       West Hill,Morningside,Guildwood
3        M1G  Scarborough                                Woburn
4        M1H  Scarborough                             Cedarbrae

### Si una celda tiene un distrito pero un vecindario no asignado, entonces el vecindario será el mismo que el distrito

In [6]:
df.loc[df['Neighborhood'] == 'Not assigned','Neighborhood'] = df['Borough']
df.head()

  PostalCode      Borough                          Neighborhood
0        M1B  Scarborough                         Rouge,Malvern
1        M1C  Scarborough  Port Union,Highland Creek,Rouge Hill
2        M1E  Scarborough       West Hill,Morningside,Guildwood
3        M1G  Scarborough                                Woburn
4        M1H  Scarborough                             Cedarbrae

### Numero de filas

In [7]:
df.shape[0]

103